spring.main.allow-circular-references: true

server:
  port: 8081
  servlet:
    context-path: /

logging.level:
  root: info

#mybatis配置
mybatis-plus:
  # 映射文件的位置
  mapper-locations: classpath:mapper/*.xml
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  # 配置包别名
  type-aliases-package:  com.snowriver.it.springdemo.entity

spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-p8m8azco.sql.tencentcdb.com:28480/trt
    username: root
    password: Eqn92Z7J
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 2000
      validationQuery: select 'x'
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher